#ifndef WMLABELS_HPP
#define WMLABELS_HPP

#ifdef AUTOCONNECT_MENULABEL_CONFIGNEW
#undef AUTOCONNECT_MENULABEL_CONFIGNEW
#define AUTOCONNECT_MENULABEL_CONFIGNEW   "New"
#endif

#ifdef AUTOCONNECT_MENULABEL_OPENSSIDS
#undef AUTOCONNECT_MENULABEL_OPENSSIDS
#define AUTOCONNECT_MENULABEL_OPENSSIDS   "Manage"
#endif

#ifdef AUTOCONNECT_PAGETITLE_CONFIG
#undef AUTOCONNECT_PAGETITLE_CONFIG
#define AUTOCONNECT_PAGETITLE_CONFIG   "New"
#endif

#ifdef AUTOCONNECT_PAGETITLE_CREDENTIALS
#undef AUTOCONNECT_PAGETITLE_CREDENTIALS
#define AUTOCONNECT_PAGETITLE_CREDENTIALS   "Manage"
#endif

#endif
