#ifndef WMLABELS_HPP
#define WMLABELS_HPP

#ifdef AUTOCONNECT_MENULABEL_CONFIGNEW
#undef AUTOCONNECT_MENULABEL_CONFIGNEW
#define AUTOCONNECT_MENULABEL_CONFIGNEW   "New"
#endif

#ifdef AUTOCONNECT_MENULABEL_OPENSSIDS
#undef AUTOCONNECT_MENULABEL_OPENSSIDS
#define AUTOCONNECT_MENULABEL_OPENSSIDS   "Manage"
#endif

#ifdef AUTOCONNECT_PAGETITLE_CONFIG
#undef AUTOCONNECT_PAGETITLE_CONFIG
#define AUTOCONNECT_PAGETITLE_CONFIG   "New"
#endif

#ifdef AUTOCONNECT_PAGETITLE_CREDENTIALS
#undef AUTOCONNECT_PAGETITLE_CREDENTIALS
#define AUTOCONNECT_PAGETITLE_CREDENTIALS   "Manage"
#endif

#ifdef AUTOCONNECT_MENUCOLOR_TEXT
#  undef  AUTOCONNECT_MENUCOLOR_TEXT
#endif
#define AUTOCONNECT_MENUCOLOR_TEXT        "#1DBCFF"

#ifdef AUTOCONNECT_MENUCOLOR_BACKGROUND
#  undef  AUTOCONNECT_MENUCOLOR_BACKGROUND
#endif
#define AUTOCONNECT_MENUCOLOR_BACKGROUND  "#070c12"

#ifdef AUTOCONNECT_MENUCOLOR_ACTIVE
#  undef  AUTOCONNECT_MENUCOLOR_ACTIVE
#endif
#define AUTOCONNECT_MENUCOLOR_ACTIVE      "#283593"

#endif
